version: '3.8'

services:
  # Serviço da API Principal (Orquestrador)
  api-principal:
    build: ./src/api
    ports:
      - "3000:3000"
    environment:
      AGENT1_CLIMA_URL: http://agent1-clima:3001
      AGENT2_ATIVIDADES_URL: http://agent2-atividades:3002
      PORT: 3000
    depends_on:
      - agent1-clima
      - agent2-atividades
    volumes:
      - ./src/api:/usr/src/app

  # Serviço do Agente 1 (Previsor de Horários Climáticos Otimizados)
  agent1-clima:
    build: ./src/agents/agent1_clima
    ports:
      - "3001:3001"
    environment:
      OPENWEATHER_API_KEY: ${OPENWEATHER_API_KEY}
      PORT: 3001
    volumes:
      - ./src/agents/agent1_clima:/usr/src/app

  # Serviço do Agente 2 (Classificador de Atividades Recomendadas)
  agent2-atividades:
    build: ./src/agents/agent2_atividades
    ports:
      - "3002:3002"
    environment:
      GEMINI_API_KEY: ${GEMINI_API_KEY} 
      PORT: 3002
    volumes:
      - ./src/agents/agent2_atividades:/usr/src/app
