# docker-compose.yml
version: '3.8'

services:
  # Serviço da API Principal (Orquestrador)
  api-principal:
    build: ./src/api
    ports:
      - "3000:3000"
    environment:
      # Referencia as variáveis do .env da raiz do projeto
      AGENT1_CLIMA_URL: http://agent1-clima:3001
      AGENT2_ATIVIDADES_URL: http://agent2-atividades:3002
      PORT: 3000
    depends_on:
      - agent1-clima
      - agent2-atividades
    volumes:
      - ./src/api:/usr/src/app

  # Serviço do Agente 1 (Previsor de Horários Climáticos Otimizados)
  agent1-clima:
    build: ./src/agents/agent1_clima
    ports:
      - "3001:3001"
    # Não precisa de env_file aqui se a chave OpenWeather for global
    # ou você pode usar 'environment' e referenciar ${OPENWEATHER_API_KEY}
    environment: # Usaremos environment aqui também para consistência
      OPENWEATHER_API_KEY: ${OPENWEATHER_API_KEY} # Referencia a chave do .env da raiz
      PORT: 3001
    volumes:
      - ./src/agents/agent1_clima:/usr/src/app

  # Serviço do Agente 2 (Classificador de Atividades Recomendadas)
  agent2-atividades:
    build: ./src/agents/agent2_atividades
    ports:
      - "3002:3002"
    environment: # Agora puxamos a chave do .env da raiz
      GEMINI_API_KEY: ${GEMINI_API_KEY} # Referencia a chave do .env da raiz
      PORT: 3002
    volumes:
      - ./src/agents/agent2_atividades:/usr/src/app
